apiVersion: v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      resources:
        cpu: "1"
        memory: "4Gi"
        volumeSize: "10Gi"
      units:
      - name: jupyter
        image: jupyter/tensorflow-notebook:latest
        env:
        - name: JUPYTER_TOKEN
          value: WorkBench

---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: jupyter
  ports:
  - name: http
    port: 80
    nodePort: 8888
    protocol: TCP
  sourceRanges:
    - 0.0.0.0/0
