apiVersion: v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      resources:
        cpu: "1"
      units:
      - name: kibana
        image: kibana:6.6.1
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:6.6.1
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: kibana
  ports:
  - name: http
    port: 80
    nodePort: 5601
    protocol: TCP
  sourceRanges:
    - 0.0.0.0/0
