---
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  instanceType: r5d.xlarge
  volumes:
  - name: shared-volume
    emptyDir: {}
  initUnits:
  - name: formatter
    image: ubuntu:bionic
    command: ["/bin/sh", "-c"]
    args: ["mkfs.ext4 -O ^has_journal /dev/nvme0n1 && mkdir /data/storage && mount /dev/nvme0n1 /data/storage -o noatime,nodiratime,barrier=0; chmod 777 /data/storage"]
    volumeMounts:
    - mountPath: /data
      name: shared-volume
  - name: init-sysctl
    image: ubuntu:bionic
    [
    command: ["sysctl", "-w", "vm.max_map_count=262144"]
  units:
  - name: elasticsearch
    image: elotl/elasticsearch:latest
    env:
    - name: "DISCOVERY_TYPE"
      value: "single-node"
    - name: "DISCOVERY_SERVICE"
      value: "elasticsearch"
    - name: ES_JAVA_OPTS
      value: -Xms256m -Xmx256m
    volumeMounts:
    - mountPath: /data
      name: shared-volume
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  ports:
    - name: elasticsearch
      port: 9200
      protocol: TCP
  sourceRanges:
    - "VPC"
