---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      resources:
        cpu: "1"
        memory: "2Gi"
      volumes:
        - name: nginx-log-shared-volume
          emptyDir: {} 
      units:
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:6.6.1
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
        - name: filebeat
          image: elotl/nginxfilebeat:latest
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-log-shared-volume
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-log-shared-volume
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: nginx
  ports:
  - name: http
    port: 80
    nodePort: 80
    protocol: TCP
  sourceRanges:
    - 0.0.0.0/0
