apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  resources:
    cpu: "1"
    memory: "4Gi"
  initUnits:
  - name: init-sysctl
    image: busybox
    command: ["sysctl", "-w", "vm.max_map_count=262144"]
  units:
  - name: elasticsearch
    image: elotl/elasticsearch:latest
    env:
    - name: "DISCOVERY_TYPE"
      value: "single-node"
    - name: "DISCOVERY_SERVICE"
      value: "elasticsearch"
    - name: ES_JAVA_OPTS
      value: -Xms256m -Xmx256m -Des.enforce.bootstrap.checks=false
