apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  resources:
    cpu: "1"
    memory: "4Gi"
  initUnits:
  - name: init-sysctl
    image: busybox
    command: ["sysctl", "-w", "vm.max_map_count=262144"]
  units:
  - name: elasticsearch
    image: elotl/elasticsearch:latest
    env:
    - name: "DISCOVERY_TYPE"
      value: "single-node"
    - name: "DISCOVERY_SERVICE"
      value: "elasticsearch"
    - name: ES_JAVA_OPTS
      value: -Xms256m -Xmx256m
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  ports:
    - name: elasticsearch
      port: 9200
      protocol: TCP
  sourceRanges:
    - "VPC"
