apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: elasticsearch
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
  sourceRanges:
    - "VPC"
