filebeat.modules:
- module: nginx
  access:
    var.paths: ["/var/log/nginx/access.log"]
  error:
    var.paths: ["/var/log/nginx/error.log"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
