---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-calculator
spec:
  selector:
    matchLabels:
      app: cost-calculator
  template:
    metadata:
      name: cost-calculator
      labels:
        app: cost-calculator
      annotations:
        kubernetes.io/target-runtime: kiyot
        pod.elotl.co/instance-type: t3.nano
    spec:
      nodeSelector:
        kubernetes.io/role: milpa-worker
      containers:
      - name: dashboard
        image: elotl/cost-calculator:0.9.2
        command: ["/usr/local/bin/gunicorn", "-k", "gevent", "-w", "3", "-b", ":5000", "--access-logfile", "-", "--error-logfile", "-", "server:app"]
      - name: https-redirect
        image: 689494258501.dkr.ecr.us-east-1.amazonaws.com/https-redirect:1.0.0

---
kind: Service
apiVersion: v1
metadata:
  name: cost-calculator  
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:689494258501:certificate/05bd8e09-9275-4c26-ad61-5de8097b770b"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: cost-calculator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
